name: 'Test'

on: [push, pull_request]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Test build
      uses: home-assistant/builder@master
      with:
        args: |
          --armhf --armv7 --aarch64 \
          --target argonOne \
          -r https://github.com/adamoutler/HassOSArgonOneAddon
          --docker-hub adamoutler/argononeactivecooling
